### ISSUE TITLE
RAW GNSS data logged in solo stock pixhawk

### ISSUE THREAD

**Issue by Roumagnifique** [OpenSolo/ardupilot-solo#2]
Hello,
I upgraded my stock pixhawk with the 1.5.4 arducopter. Unfortunatly, it is still not possible to log the raw gps/gnss data as GPS_RAW_DATA ables to do it in newer version of arducopter :-/ 
Are you going to add this function in the next release?

Yhanks for your works!

Seb

**Comment by davidbuzz** [comment]
PR's welcome!
