### ISSUE TITLE
how to load my code to the 3DR solo

### ISSUE THREAD

**Issue by Tenacity-soar** [OpenSolo/ardupilot-solo#3]
I modified the source code for my experiment. But i don't know how to load my code to the 3DR solo.  Can you help me, thanks!!!

**Comment by davidbuzz** [comment]
Did u read the documentation at https://github.com/OpenSolo/documentation/blob/master/README.md ? Especially the "for developers" section?

**Comment by Tenacity-soar** [comment]
thanks.  I have read the documentation.  I know how to load my code to the 3DR solo.  But now i am confused with another problem.   When i build my code use ./waf configure --board px4-v3   and 
./waf copter
a problem happen
/home/shangsuning/ardupilot/modules/PX4Firmware/makefiles/firmware.mk:519: recipe for target '/home/shangsuning/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.elf' failed
make[2]: *** [/home/shangsuning/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.elf] Error 1
make[2]: Leaving directory '/home/shangsuning/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build'
/home/shangsuning/ardupilot/modules/PX4Firmware/Makefile.make:143: recipe for target '/home/shangsuning/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.px4' failed
make[1]: *** [/home/shangsuning/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.px4] Error 2
make[1]: Leaving directory '/home/shangsuning/ardupilot'
../mk/px4_targets.mk:109: recipe for target 'px4-v3' failed
make: *** [px4-v3] Error 2
can you help me ? thanks

**Comment by Tenacity-soar** [comment]
I have solve this problem. Thanks
