### ISSUE TITLE
How to build the ardupilot-solo?

### ISSUE THREAD

**Issue by Tenacity-soar** [OpenSolo/ardupilot-solo#4]
I have git the ardupilot-solo.   But i don't know how to build it.  
I know how to build the ardupilot, but how to build the ardupilot-solo?

**Comment by davidbuzz** [comment]
have you looked here..? https://github.com/OpenSolo/solo-builder

**Comment by Tenacity-soar** [comment]
thank you very much. 
I have read the http://ardupilot.org/dev/docs/solo.html 
I followed that webpage, then i met some mistake.  maybe that webpage is not contain the solo.
I will look https://github.com/OpenSolo/solo-builder  . thank you .

**Comment by Tenacity-soar** [comment]
> have you looked here..? https://github.com/OpenSolo/solo-builder

Thank you very much. I have looked https://github.com/OpenSolo/solo-builder. But the webpage is building the entire software, I only want to generate the ArduCopter-v2.px4 file

I want to know how to generate the ArduCopter-v2.px4 file?  I know how to load the ArduCopter-2.px4 to the uav.

So how to generate the ArduCopter-v2.px4 file?

**Comment by Tenacity-soar** [comment]
thank you very much. I have made some attempts. But i met some problems. My goal is to generate the ArduCopter-v2.px4 file.
1.git clone https://github.com/ArduPilot/ardupilot
2.cd ardupilot
3.git submodule update --init --recursive
4.Tools/scripts/install-prereqs-ubuntu.sh -y
5.. ~/.profile
6../waf configure --board px4-v3
7../waf copter
then i get the arducopter.px4 file
I use the scp command to upload the arducopter.px4 to root@10.1.1.10:/firmware/
then i reboot the 3DR solo UAV. But some problem happened.
I guess the reason is that ardupilot codes is not suit for the 3DR solo UAV.
then i try to build the ardupilot-solo use waf/make.  But 

make: *** No targets specified and no makefile found.  Stop.
bash: ./waf: No such file or directory

So i want to know how to build the ardupilot-solo and generate the ArduCopter-v2.px4(https://github.com/OpenSolo/ardupilot-solo/releases)

Can you help me ? thanks

**Comment by davidbuzz** [comment]
you appear to be compiling the mainstream "ArduPilot" code, not the OpenSolo one. This "issue" is no longer about a bug/problem/error in OpenSolo itself, and seems more to do with your lack of understanding about what code to use, and where.    I'm closing this as invalid.   If you solve your issue, and would like to give back to the community, please document what you are trying to do, and add it to the documentation site  as a PR.  ( https://github.com/OpenSolo/documentation )

**Comment by Tenacity-soar** [comment]
thank you. I am following http://ardupilot.org/dev/docs/solo-opensolo-quickstart.html#opensolo-quickstart-guide.   Can you let me know that http://ardupilot.org/dev/docs/solo-opensolo-quickstart.html#opensolo-quickstart-guide this webpage is right for building the ardupilot-solo?  Can i generate ArduCopter-v2.px4?
